// Generated by generate.ts - DO NOT EDIT
// Generated: 2026-01-09T18:18:01.882Z
// Source: patterns/patterns.yaml (cf55af4b800c), patterns/env.yaml (e13e81c332a5)

export const LONG_THRESHOLD = 50;
export const MAX_PRIVATE_KEY_BUFFER = 100;

export const PRIVATE_KEY_BEGIN = /-----BEGIN [A-Z ]*PRIVATE KEY-----/;
export const PRIVATE_KEY_END = /-----END [A-Z ]*PRIVATE KEY-----/;

export const PATTERNS: [RegExp, string][] = [
  [/ghp_[A-Za-z0-9]{36}/g, 'GITHUB_PAT'],
  [/gho_[A-Za-z0-9]{36}/g, 'GITHUB_OAUTH'],
  [/ghs_[A-Za-z0-9]{36}/g, 'GITHUB_SERVER'],
  [/ghr_[A-Za-z0-9]{36}/g, 'GITHUB_REFRESH'],
  [/github_pat_[A-Za-z0-9_]{22,}/g, 'GITHUB_PAT'],
  [/glpat-[A-Za-z0-9_-]{20,}/g, 'GITLAB_PAT'],
  [/xoxb-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_BOT'],
  [/xoxp-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_USER'],
  [/xoxa-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_APP'],
  [/xoxs-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_SESSION'],
  [/sk-[A-Za-z0-9]{48}/g, 'OPENAI_KEY'],
  [/sk-proj-[A-Za-z0-9_-]{20,}/g, 'OPENAI_PROJECT_KEY'],
  [/sk-ant-[A-Za-z0-9-]{90,}/g, 'ANTHROPIC_KEY'],
  [/AKIA[A-Z0-9]{16}/g, 'AWS_ACCESS_KEY'],
  [/AIza[A-Za-z0-9_-]{35}/g, 'GOOGLE_API_KEY'],
  [/AGE-SECRET-KEY-[A-Z0-9]{59}/g, 'AGE_SECRET_KEY'],
  [/sk_live_[A-Za-z0-9]{24,}/g, 'STRIPE_SECRET'],
  [/sk_test_[A-Za-z0-9]{24,}/g, 'STRIPE_TEST'],
  [/pk_live_[A-Za-z0-9]{24,}/g, 'STRIPE_PUBLISHABLE'],
  [/SK[a-f0-9]{32}/g, 'TWILIO_KEY'],
  [/SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g, 'SENDGRID_KEY'],
  [/npm_[A-Za-z0-9]{36}/g, 'NPM_TOKEN'],
  [/pypi-[A-Za-z0-9_-]{100,}/g, 'PYPI_TOKEN'],
  [/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g, 'JWT_TOKEN'],
];

export const CONTEXT_PATTERNS: [RegExp, string][] = [
  [/(?<=password )[^\s]+/g, 'NETRC_PASSWORD'],
  [/(?<=passwd )[^\s]+/g, 'NETRC_PASSWORD'],
  [/(?<=password=)[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=password:)\s*[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=secret=)[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=secret:)\s*[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=token=)[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
  [/(?<=token:)\s*[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
  [/(?<=Password=)[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=Password:)\s*[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=Secret=)[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=Secret:)\s*[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=Token=)[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
  [/(?<=Token:)\s*[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
];

export interface SpecialPatternInfo {
  pattern: RegExp;
  label: string;
  secretGroup: number;
}

export const SPECIAL_PATTERNS: Record<string, SpecialPatternInfo> = {
  git_credential: {
    pattern: /(:\/\/[^:]+:)([^@]+)(@)/g,
    label: 'GIT_CREDENTIAL',
    secretGroup: 2,
  },
  docker_auth: {
    pattern: /("auth":\s*")([A-Za-z0-9+\/=]{20,})(")/g,
    label: 'DOCKER_AUTH',
    secretGroup: 2,
  },
};

// Multiline pattern for batch mode fallback
export const PRIVATE_KEY_MULTILINE: [RegExp, string] = [/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g, 'PRIVATE_KEY'];

export const EXPLICIT_ENV_VARS = new Set([
  'GITHUB_TOKEN',
  'GH_TOKEN',
  'GITLAB_TOKEN',
  'GLAB_TOKEN',
  'BITBUCKET_TOKEN',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_SESSION_TOKEN',
  'AZURE_CLIENT_SECRET',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'CLAUDE_API_KEY',
  'SLACK_TOKEN',
  'SLACK_BOT_TOKEN',
  'SLACK_WEBHOOK_URL',
  'NPM_TOKEN',
  'PYPI_TOKEN',
  'DOCKER_PASSWORD',
  'DATABASE_URL',
  'REDIS_URL',
  'MONGODB_URI',
  'JWT_SECRET',
  'SESSION_SECRET',
  'ENCRYPTION_KEY',
  'SENDGRID_API_KEY',
  'TWILIO_AUTH_TOKEN',
  'STRIPE_SECRET_KEY',
]);

export const ENV_SUFFIXES: string[] = [
  '_SECRET',
  '_PASSWORD',
  '_TOKEN',
  '_API_KEY',
  '_PRIVATE_KEY',
  '_AUTH',
  '_CREDENTIAL',
];
