// Generated by generate.ts - DO NOT EDIT
// Generated: 2026-01-09T18:46:56.906Z
// Source: patterns/patterns.yaml (81fdf7816541), patterns/env.yaml (dfab996443dc)

export const LONG_THRESHOLD = 50;
export const MAX_PRIVATE_KEY_BUFFER = 100;

export const PRIVATE_KEY_BEGIN = /-----BEGIN [A-Z ]*PRIVATE KEY-----/;
export const PRIVATE_KEY_END = /-----END [A-Z ]*PRIVATE KEY-----/;

export const PATTERNS: [RegExp, string][] = [
  [/ghp_[A-Za-z0-9]{36}/g, 'GITHUB_PAT'],
  [/gho_[A-Za-z0-9]{36}/g, 'GITHUB_OAUTH'],
  [/ghs_[A-Za-z0-9]{36}/g, 'GITHUB_SERVER'],
  [/ghr_[A-Za-z0-9]{36}/g, 'GITHUB_REFRESH'],
  [/github_pat_[A-Za-z0-9_]{22,}/g, 'GITHUB_PAT'],
  [/glpat-[A-Za-z0-9_-]{20,}/g, 'GITLAB_PAT'],
  [/xoxb-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_BOT'],
  [/xoxp-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_USER'],
  [/xoxa-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_APP'],
  [/xoxs-[0-9]+-[0-9A-Za-z-]+/g, 'SLACK_SESSION'],
  [/sk-[A-Za-z0-9]{48}/g, 'OPENAI_KEY'],
  [/sk-proj-[A-Za-z0-9_-]{20,}/g, 'OPENAI_PROJECT_KEY'],
  [/sk-ant-[A-Za-z0-9-]{90,}/g, 'ANTHROPIC_KEY'],
  [/AKIA[A-Z0-9]{16}/g, 'AWS_ACCESS_KEY'],
  [/AIza[A-Za-z0-9_-]{35}/g, 'GOOGLE_API_KEY'],
  [/AGE-SECRET-KEY-[A-Z0-9]{59}/g, 'AGE_SECRET_KEY'],
  [/sk_live_[A-Za-z0-9]{24,}/g, 'STRIPE_SECRET'],
  [/sk_test_[A-Za-z0-9]{24,}/g, 'STRIPE_TEST'],
  [/pk_live_[A-Za-z0-9]{24,}/g, 'STRIPE_PUBLISHABLE'],
  [/SK[a-f0-9]{32}/g, 'TWILIO_KEY'],
  [/SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g, 'SENDGRID_KEY'],
  [/npm_[A-Za-z0-9]{36}/g, 'NPM_TOKEN'],
  [/pypi-[A-Za-z0-9_-]{100,}/g, 'PYPI_TOKEN'],
  [/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g, 'JWT_TOKEN'],
  [/dop_v1_[a-f0-9]{64}/g, 'DIGITALOCEAN_PAT'],
  [/doo_v1_[a-f0-9]{64}/g, 'DIGITALOCEAN_OAUTH'],
  [/dor_v1_[a-f0-9]{64}/g, 'DIGITALOCEAN_REFRESH'],
  [/HRKU-[A-Za-z0-9_]{60}/g, 'HEROKU_API_KEY'],
  [/GOCSPX-[A-Za-z0-9_-]{20,}/g, 'GCP_OAUTH_SECRET'],
  [/nfp_[A-Za-z0-9_-]{20,}/g, 'NETLIFY_PAT'],
  [/sb_publishable_[A-Za-z0-9_-]{20,}/g, 'SUPABASE_PUBLISHABLE'],
  [/sb_secret_[A-Za-z0-9_-]{20,}/g, 'SUPABASE_SECRET'],
  [/pscale_tkn_[A-Za-z0-9_-]{30,}/g, 'PLANETSCALE_TOKEN'],
  [/[A-Za-z0-9]{9}\.atlasv1\.[A-Za-z0-9]{40,}/g, 'TERRAFORM_CLOUD_TOKEN'],
  [/hvs\.[A-Za-z0-9]{24,}/g, 'VAULT_SERVICE_TOKEN'],
  [/hvb\.[A-Za-z0-9]{24,}/g, 'VAULT_BATCH_TOKEN'],
  [/hvr\.[A-Za-z0-9]{24,}/g, 'VAULT_RECOVERY_TOKEN'],
  [/rubygems_[a-f0-9]{56}/g, 'RUBYGEMS_API_KEY'],
  [/shpat_[A-Za-z0-9]{32,}/g, 'SHOPIFY_ADMIN_TOKEN'],
  [/NRAK-[A-Za-z0-9]{27,}/g, 'NEWRELIC_USER_KEY'],
  [/key-[A-Za-z0-9]{32,}/g, 'MAILGUN_API_KEY'],
  [/lin_api_[A-Za-z0-9]{40,}/g, 'LINEAR_API_KEY'],
  [/dp\.pt\.[A-Za-z0-9]{40,}/g, 'DOPPLER_TOKEN'],
  [/[0-9]{9,10}:[A-Za-z0-9_-]{35,}/g, 'TELEGRAM_BOT_TOKEN'],
  [/[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}/g, 'DISCORD_BOT_TOKEN'],
  [/https:\/\/discord\.com\/api\/webhooks\/[0-9]+\/[A-Za-z0-9_-]+/g, 'DISCORD_WEBHOOK'],
  [/EAA[A-Za-z0-9]{50,}/g, 'FACEBOOK_ACCESS_TOKEN'],
];

export const CONTEXT_PATTERNS: [RegExp, string][] = [
  [/(?<=password )[^\s]+/g, 'NETRC_PASSWORD'],
  [/(?<=passwd )[^\s]+/g, 'NETRC_PASSWORD'],
  [/(?<=password=)[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=password:)\s*[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=secret=)[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=secret:)\s*[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=token=)[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
  [/(?<=token:)\s*[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
  [/(?<=AccountKey=)[A-Za-z0-9+\/]{88}==/g, 'AZURE_STORAGE_KEY'],
  [/(?<=Password=)[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=Password:)\s*[^\s,;"'\}\[\]]+/g, 'PASSWORD_VALUE'],
  [/(?<=Secret=)[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=Secret:)\s*[^\s,;"'\}\[\]]+/g, 'SECRET_VALUE'],
  [/(?<=Token=)[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
  [/(?<=Token:)\s*[^\s,;"'\}\[\]]+/g, 'TOKEN_VALUE'],
];

export interface SpecialPatternInfo {
  pattern: RegExp;
  label: string;
  secretGroup: number;
}

export const SPECIAL_PATTERNS: Record<string, SpecialPatternInfo> = {
  git_credential: {
    pattern: /(:\/\/[^:]+:)([^@]+)(@)/g,
    label: 'GIT_CREDENTIAL',
    secretGroup: 2,
  },
  docker_auth: {
    pattern: /("auth":\s*")([A-Za-z0-9+\/=]{20,})(")/g,
    label: 'DOCKER_AUTH',
    secretGroup: 2,
  },
};

// Multiline pattern for batch mode fallback
export const PRIVATE_KEY_MULTILINE: [RegExp, string] = [/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g, 'PRIVATE_KEY'];

export const EXPLICIT_ENV_VARS = new Set([
  'GITHUB_TOKEN',
  'GH_TOKEN',
  'GITLAB_TOKEN',
  'GLAB_TOKEN',
  'BITBUCKET_TOKEN',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_SESSION_TOKEN',
  'AZURE_CLIENT_SECRET',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'CLAUDE_API_KEY',
  'SLACK_TOKEN',
  'SLACK_BOT_TOKEN',
  'SLACK_WEBHOOK_URL',
  'NPM_TOKEN',
  'PYPI_TOKEN',
  'DOCKER_PASSWORD',
  'DATABASE_URL',
  'REDIS_URL',
  'MONGODB_URI',
  'JWT_SECRET',
  'SESSION_SECRET',
  'ENCRYPTION_KEY',
  'SENDGRID_API_KEY',
  'TWILIO_AUTH_TOKEN',
  'STRIPE_SECRET_KEY',
  'DIGITALOCEAN_TOKEN',
  'DIGITALOCEAN_ACCESS_TOKEN',
  'HEROKU_API_KEY',
  'HEROKU_AUTH_TOKEN',
  'NETLIFY_AUTH_TOKEN',
  'VERCEL_TOKEN',
  'CLOUDFLARE_API_TOKEN',
  'CLOUDFLARE_API_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_ANON_KEY',
  'PLANETSCALE_SERVICE_TOKEN',
  'NEON_API_KEY',
  'VAULT_TOKEN',
  'TF_TOKEN',
  'TFC_TOKEN',
  'TERRAFORM_CLOUD_TOKEN',
  'CONSUL_HTTP_TOKEN',
  'DISCORD_TOKEN',
  'DISCORD_BOT_TOKEN',
  'TELEGRAM_BOT_TOKEN',
  'DATADOG_API_KEY',
  'DATADOG_APP_KEY',
  'NEW_RELIC_LICENSE_KEY',
  'NEWRELIC_API_KEY',
  'SENTRY_DSN',
  'SENTRY_AUTH_TOKEN',
  'GRAFANA_API_KEY',
  'LINEAR_API_KEY',
  'DOPPLER_TOKEN',
  'SHOPIFY_ACCESS_TOKEN',
  'SHOPIFY_API_KEY',
  'SHOPIFY_API_SECRET',
  'MAILGUN_API_KEY',
  'ALGOLIA_API_KEY',
  'ALGOLIA_ADMIN_KEY',
  'FACEBOOK_ACCESS_TOKEN',
]);

export const ENV_SUFFIXES: string[] = [
  '_SECRET',
  '_PASSWORD',
  '_TOKEN',
  '_API_KEY',
  '_PRIVATE_KEY',
  '_AUTH',
  '_CREDENTIAL',
];
