#!/usr/bin/env bash
# Clean build artifacts
set -euo pipefail
cd "$(dirname "$0")"

echo "Cleaning build artifacts..."

# Rust build artifacts
rm -rf target/

# Build output
rm -rf build/

# Generated patterns (regenerated by build)
rm -f src/patterns_gen.rs

echo "Done."
