// Code generated by generate.rs - DO NOT EDIT
// Source: patterns/*.yaml (hash: cda5969325d4)
// Generated: 2026-01-09T18:46:59Z

// Constants from patterns.yaml
pub const LONG_THRESHOLD: usize = 50;
pub const MAX_PRIVATE_KEY_BUFFER: usize = 100;

// Private key markers (for streaming state machine)
pub const PRIVATE_KEY_BEGIN: &str = r"-----BEGIN [A-Z ]*PRIVATE KEY-----";
pub const PRIVATE_KEY_END: &str = r"-----END [A-Z ]*PRIVATE KEY-----";

/// Direct patterns: (regex, label)
/// Match these patterns directly without context
pub const PATTERNS: &[(&str, &str)] = &[
    (r"ghp_[A-Za-z0-9]{36}", "GITHUB_PAT"),
    (r"gho_[A-Za-z0-9]{36}", "GITHUB_OAUTH"),
    (r"ghs_[A-Za-z0-9]{36}", "GITHUB_SERVER"),
    (r"ghr_[A-Za-z0-9]{36}", "GITHUB_REFRESH"),
    (r"github_pat_[A-Za-z0-9_]{22,}", "GITHUB_PAT"),
    (r"glpat-[A-Za-z0-9_-]{20,}", "GITLAB_PAT"),
    (r"xoxb-[0-9]+-[0-9A-Za-z-]+", "SLACK_BOT"),
    (r"xoxp-[0-9]+-[0-9A-Za-z-]+", "SLACK_USER"),
    (r"xoxa-[0-9]+-[0-9A-Za-z-]+", "SLACK_APP"),
    (r"xoxs-[0-9]+-[0-9A-Za-z-]+", "SLACK_SESSION"),
    (r"sk-[A-Za-z0-9]{48}", "OPENAI_KEY"),
    (r"sk-proj-[A-Za-z0-9_-]{20,}", "OPENAI_PROJECT_KEY"),
    (r"sk-ant-[A-Za-z0-9-]{90,}", "ANTHROPIC_KEY"),
    (r"AKIA[A-Z0-9]{16}", "AWS_ACCESS_KEY"),
    (r"AIza[A-Za-z0-9_-]{35}", "GOOGLE_API_KEY"),
    (r"AGE-SECRET-KEY-[A-Z0-9]{59}", "AGE_SECRET_KEY"),
    (r"sk_live_[A-Za-z0-9]{24,}", "STRIPE_SECRET"),
    (r"sk_test_[A-Za-z0-9]{24,}", "STRIPE_TEST"),
    (r"pk_live_[A-Za-z0-9]{24,}", "STRIPE_PUBLISHABLE"),
    (r"SK[a-f0-9]{32}", "TWILIO_KEY"),
    (r"SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+", "SENDGRID_KEY"),
    (r"npm_[A-Za-z0-9]{36}", "NPM_TOKEN"),
    (r"pypi-[A-Za-z0-9_-]{100,}", "PYPI_TOKEN"),
    (r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+", "JWT_TOKEN"),
    (r"dop_v1_[a-f0-9]{64}", "DIGITALOCEAN_PAT"),
    (r"doo_v1_[a-f0-9]{64}", "DIGITALOCEAN_OAUTH"),
    (r"dor_v1_[a-f0-9]{64}", "DIGITALOCEAN_REFRESH"),
    (r"HRKU-[A-Za-z0-9_]{60}", "HEROKU_API_KEY"),
    (r"GOCSPX-[A-Za-z0-9_-]{20,}", "GCP_OAUTH_SECRET"),
    (r"nfp_[A-Za-z0-9_-]{20,}", "NETLIFY_PAT"),
    (r"sb_publishable_[A-Za-z0-9_-]{20,}", "SUPABASE_PUBLISHABLE"),
    (r"sb_secret_[A-Za-z0-9_-]{20,}", "SUPABASE_SECRET"),
    (r"pscale_tkn_[A-Za-z0-9_-]{30,}", "PLANETSCALE_TOKEN"),
    (r"[A-Za-z0-9]{9}\.atlasv1\.[A-Za-z0-9]{40,}", "TERRAFORM_CLOUD_TOKEN"),
    (r"hvs\.[A-Za-z0-9]{24,}", "VAULT_SERVICE_TOKEN"),
    (r"hvb\.[A-Za-z0-9]{24,}", "VAULT_BATCH_TOKEN"),
    (r"hvr\.[A-Za-z0-9]{24,}", "VAULT_RECOVERY_TOKEN"),
    (r"rubygems_[a-f0-9]{56}", "RUBYGEMS_API_KEY"),
    (r"shpat_[A-Za-z0-9]{32,}", "SHOPIFY_ADMIN_TOKEN"),
    (r"NRAK-[A-Za-z0-9]{27,}", "NEWRELIC_USER_KEY"),
    (r"key-[A-Za-z0-9]{32,}", "MAILGUN_API_KEY"),
    (r"lin_api_[A-Za-z0-9]{40,}", "LINEAR_API_KEY"),
    (r"dp\.pt\.[A-Za-z0-9]{40,}", "DOPPLER_TOKEN"),
    (r"[0-9]{9,10}:[A-Za-z0-9_-]{35,}", "TELEGRAM_BOT_TOKEN"),
    (r"[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}", "DISCORD_BOT_TOKEN"),
    (r"https://discord\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+", "DISCORD_WEBHOOK"),
    (r"EAA[A-Za-z0-9]{50,}", "FACEBOOK_ACCESS_TOKEN"),
];

/// Context patterns: (regex, label, capture_group)
/// Rust regex lacks lookbehind - use capture groups instead
/// The secret value is in the specified capture group
pub const CONTEXT_PATTERNS: &[(&str, &str, usize)] = &[
    (r"(password )([^\s]+)", "NETRC_PASSWORD", 2),
    (r"(passwd )([^\s]+)", "NETRC_PASSWORD", 2),
    (r#"(password=)([^\s,;"'\}\[\]]+)"#, "PASSWORD_VALUE", 2),
    (r#"(password:)(\s*[^\s,;"'\}\[\]]+)"#, "PASSWORD_VALUE", 2),
    (r#"(secret=)([^\s,;"'\}\[\]]+)"#, "SECRET_VALUE", 2),
    (r#"(secret:)(\s*[^\s,;"'\}\[\]]+)"#, "SECRET_VALUE", 2),
    (r#"(token=)([^\s,;"'\}\[\]]+)"#, "TOKEN_VALUE", 2),
    (r#"(token:)(\s*[^\s,;"'\}\[\]]+)"#, "TOKEN_VALUE", 2),
    (r"(AccountKey=)([A-Za-z0-9+/]{88}==)", "AZURE_STORAGE_KEY", 2),
    (r#"(Password=)([^\s,;"'\}\[\]]+)"#, "PASSWORD_VALUE", 2),
    (r#"(Password:)(\s*[^\s,;"'\}\[\]]+)"#, "PASSWORD_VALUE", 2),
    (r#"(Secret=)([^\s,;"'\}\[\]]+)"#, "SECRET_VALUE", 2),
    (r#"(Secret:)(\s*[^\s,;"'\}\[\]]+)"#, "SECRET_VALUE", 2),
    (r#"(Token=)([^\s,;"'\}\[\]]+)"#, "TOKEN_VALUE", 2),
    (r#"(Token:)(\s*[^\s,;"'\}\[\]]+)"#, "TOKEN_VALUE", 2),
];

/// Special pattern configuration
#[derive(Debug, Clone)]
pub struct SpecialPattern {
    pub pattern: &'static str,
    pub label: &'static str,
    pub secret_group: usize,
}

pub const GIT_CREDENTIAL_PATTERN: SpecialPattern = SpecialPattern {
    pattern: r"(://[^:]+:)([^@]+)(@)",
    label: "GIT_CREDENTIAL",
    secret_group: 2,
};

pub const DOCKER_AUTH_PATTERN: SpecialPattern = SpecialPattern {
    pattern: r#"("auth":\s*")([A-Za-z0-9+/=]{20,})(")"#,
    label: "DOCKER_AUTH",
    secret_group: 2,
};

// Environment variable detection rules from env.yaml

/// Explicit list of known secret variable names
pub const EXPLICIT_ENV_VARS: &[&str] = &[
    "GITHUB_TOKEN",
    "GH_TOKEN",
    "GITLAB_TOKEN",
    "GLAB_TOKEN",
    "BITBUCKET_TOKEN",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
    "AZURE_CLIENT_SECRET",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "CLAUDE_API_KEY",
    "SLACK_TOKEN",
    "SLACK_BOT_TOKEN",
    "SLACK_WEBHOOK_URL",
    "NPM_TOKEN",
    "PYPI_TOKEN",
    "DOCKER_PASSWORD",
    "DATABASE_URL",
    "REDIS_URL",
    "MONGODB_URI",
    "JWT_SECRET",
    "SESSION_SECRET",
    "ENCRYPTION_KEY",
    "SENDGRID_API_KEY",
    "TWILIO_AUTH_TOKEN",
    "STRIPE_SECRET_KEY",
    "DIGITALOCEAN_TOKEN",
    "DIGITALOCEAN_ACCESS_TOKEN",
    "HEROKU_API_KEY",
    "HEROKU_AUTH_TOKEN",
    "NETLIFY_AUTH_TOKEN",
    "VERCEL_TOKEN",
    "CLOUDFLARE_API_TOKEN",
    "CLOUDFLARE_API_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
    "SUPABASE_ANON_KEY",
    "PLANETSCALE_SERVICE_TOKEN",
    "NEON_API_KEY",
    "VAULT_TOKEN",
    "TF_TOKEN",
    "TFC_TOKEN",
    "TERRAFORM_CLOUD_TOKEN",
    "CONSUL_HTTP_TOKEN",
    "DISCORD_TOKEN",
    "DISCORD_BOT_TOKEN",
    "TELEGRAM_BOT_TOKEN",
    "DATADOG_API_KEY",
    "DATADOG_APP_KEY",
    "NEW_RELIC_LICENSE_KEY",
    "NEWRELIC_API_KEY",
    "SENTRY_DSN",
    "SENTRY_AUTH_TOKEN",
    "GRAFANA_API_KEY",
    "LINEAR_API_KEY",
    "DOPPLER_TOKEN",
    "SHOPIFY_ACCESS_TOKEN",
    "SHOPIFY_API_KEY",
    "SHOPIFY_API_SECRET",
    "MAILGUN_API_KEY",
    "ALGOLIA_API_KEY",
    "ALGOLIA_ADMIN_KEY",
    "FACEBOOK_ACCESS_TOKEN",
];

/// Variable name suffixes that indicate secrets
pub const ENV_SUFFIXES: &[&str] = &[
    "_SECRET",
    "_PASSWORD",
    "_TOKEN",
    "_API_KEY",
    "_PRIVATE_KEY",
    "_AUTH",
    "_CREDENTIAL",
];
