// Code generated by generate.swift - DO NOT EDIT
// Generated: 2026-01-09 19:14:34
// Source: patterns/patterns.yaml (hash: cf55af4b800c)
//         patterns/env.yaml (hash: e13e81c332a5)

import Foundation

// MARK: - Constants

let longThreshold = 50
let maxPrivateKeyBuffer = 100

// MARK: - Direct Patterns
// Patterns that can be matched without context

let patterns: [(pattern: String, label: String)] = [
    ("ghp_[A-Za-z0-9]{36}", "GITHUB_PAT"),
    ("gho_[A-Za-z0-9]{36}", "GITHUB_OAUTH"),
    ("ghs_[A-Za-z0-9]{36}", "GITHUB_SERVER"),
    ("ghr_[A-Za-z0-9]{36}", "GITHUB_REFRESH"),
    ("github_pat_[A-Za-z0-9_]{22,}", "GITHUB_PAT"),
    ("glpat-[A-Za-z0-9_-]{20,}", "GITLAB_PAT"),
    ("xoxb-[0-9]+-[0-9A-Za-z-]+", "SLACK_BOT"),
    ("xoxp-[0-9]+-[0-9A-Za-z-]+", "SLACK_USER"),
    ("xoxa-[0-9]+-[0-9A-Za-z-]+", "SLACK_APP"),
    ("xoxs-[0-9]+-[0-9A-Za-z-]+", "SLACK_SESSION"),
    ("sk-[A-Za-z0-9]{48}", "OPENAI_KEY"),
    ("sk-proj-[A-Za-z0-9_-]{20,}", "OPENAI_PROJECT_KEY"),
    ("sk-ant-[A-Za-z0-9-]{90,}", "ANTHROPIC_KEY"),
    ("AKIA[A-Z0-9]{16}", "AWS_ACCESS_KEY"),
    ("AIza[A-Za-z0-9_-]{35}", "GOOGLE_API_KEY"),
    ("AGE-SECRET-KEY-[A-Z0-9]{59}", "AGE_SECRET_KEY"),
    ("sk_live_[A-Za-z0-9]{24,}", "STRIPE_SECRET"),
    ("sk_test_[A-Za-z0-9]{24,}", "STRIPE_TEST"),
    ("pk_live_[A-Za-z0-9]{24,}", "STRIPE_PUBLISHABLE"),
    ("SK[a-f0-9]{32}", "TWILIO_KEY"),
    ("SG\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+", "SENDGRID_KEY"),
    ("npm_[A-Za-z0-9]{36}", "NPM_TOKEN"),
    ("pypi-[A-Za-z0-9_-]{100,}", "PYPI_TOKEN"),
    ("eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+", "JWT_TOKEN")
]

// MARK: - Context Patterns
// Patterns that require a prefix context (using capture groups)
// Format: (pattern, label, secretGroup)
// The pattern uses capture groups: group 1 = prefix, group 2 = secret value

let contextPatterns: [(pattern: String, label: String, group: Int)] = [
    ("(password )([^\\s]+)", "NETRC_PASSWORD", 2),
    ("(passwd )([^\\s]+)", "NETRC_PASSWORD", 2),
    ("(password=)([^\\s,;\"'\\}\\[\\]]+)", "PASSWORD_VALUE", 2),
    ("(password:)(\\s*[^\\s,;\"'\\}\\[\\]]+)", "PASSWORD_VALUE", 2),
    ("(secret=)([^\\s,;\"'\\}\\[\\]]+)", "SECRET_VALUE", 2),
    ("(secret:)(\\s*[^\\s,;\"'\\}\\[\\]]+)", "SECRET_VALUE", 2),
    ("(token=)([^\\s,;\"'\\}\\[\\]]+)", "TOKEN_VALUE", 2),
    ("(token:)(\\s*[^\\s,;\"'\\}\\[\\]]+)", "TOKEN_VALUE", 2),
    ("(Password=)([^\\s,;\"'\\}\\[\\]]+)", "PASSWORD_VALUE", 2),
    ("(Password:)(\\s*[^\\s,;\"'\\}\\[\\]]+)", "PASSWORD_VALUE", 2),
    ("(Secret=)([^\\s,;\"'\\}\\[\\]]+)", "SECRET_VALUE", 2),
    ("(Secret:)(\\s*[^\\s,;\"'\\}\\[\\]]+)", "SECRET_VALUE", 2),
    ("(Token=)([^\\s,;\"'\\}\\[\\]]+)", "TOKEN_VALUE", 2),
    ("(Token:)(\\s*[^\\s,;\"'\\}\\[\\]]+)", "TOKEN_VALUE", 2)
]

// MARK: - Special Patterns
// Complex patterns with multiple capture groups

struct SpecialPattern {
    let pattern: String
    let label: String
    let secretGroup: Int
}

let gitCredentialPattern = SpecialPattern(
    pattern: "(://[^:]+:)([^@]+)(@)",
    label: "GIT_CREDENTIAL",
    secretGroup: 2
)

let dockerAuthPattern = SpecialPattern(
    pattern: "(\"auth\":\\s*\")([A-Za-z0-9+/=]{20,})(\")",
    label: "DOCKER_AUTH",
    secretGroup: 2
)

// MARK: - Private Key Markers

let privateKeyBeginPattern = "-----BEGIN [A-Z ]*PRIVATE KEY-----"
let privateKeyEndPattern = "-----END [A-Z ]*PRIVATE KEY-----"

// MARK: - Environment Variable Detection

let explicitEnvVars: Set<String> = [
    "GITHUB_TOKEN",
    "GH_TOKEN",
    "GITLAB_TOKEN",
    "GLAB_TOKEN",
    "BITBUCKET_TOKEN",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
    "AZURE_CLIENT_SECRET",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "CLAUDE_API_KEY",
    "SLACK_TOKEN",
    "SLACK_BOT_TOKEN",
    "SLACK_WEBHOOK_URL",
    "NPM_TOKEN",
    "PYPI_TOKEN",
    "DOCKER_PASSWORD",
    "DATABASE_URL",
    "REDIS_URL",
    "MONGODB_URI",
    "JWT_SECRET",
    "SESSION_SECRET",
    "ENCRYPTION_KEY",
    "SENDGRID_API_KEY",
    "TWILIO_AUTH_TOKEN",
    "STRIPE_SECRET_KEY"
]

let envSuffixes: [String] = [
    "_SECRET",
    "_PASSWORD",
    "_TOKEN",
    "_API_KEY",
    "_PRIVATE_KEY",
    "_AUTH",
    "_CREDENTIAL"
]
