#!/usr/bin/env bash
# Generate patterns_gen.rs from YAML pattern definitions
# Despite the .rs extension, this is a bash script that generates Rust code.
# The .rs extension clarifies its purpose (generating Rust patterns).
#
# Usage: ./generate.rs
# Output: src/patterns_gen.rs

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATTERNS_DIR="$SCRIPT_DIR/../patterns"
OUTPUT="$SCRIPT_DIR/src/patterns_gen.rs"

# Check dependencies
command -v yq >/dev/null 2>&1 || { echo "Error: yq is required" >&2; exit 1; }

# Compute source hash for tracking (portable: sha256sum on Linux, shasum on macOS)
if command -v sha256sum >/dev/null 2>&1; then
    patterns_hash=$(cat "$PATTERNS_DIR/patterns.yaml" "$PATTERNS_DIR/env.yaml" "$PATTERNS_DIR/entropy.yaml" 2>/dev/null | sha256sum | cut -c1-12)
else
    patterns_hash=$(cat "$PATTERNS_DIR/patterns.yaml" "$PATTERNS_DIR/env.yaml" "$PATTERNS_DIR/entropy.yaml" 2>/dev/null | shasum -a 256 | cut -c1-12)
fi
timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Helper: format a pattern as a Rust raw string literal
# Uses r#"..."# if pattern contains quotes, otherwise r"..."
rust_raw_string() {
    local pattern="$1"
    if [[ "$pattern" == *'"'* ]]; then
        echo "r#\"$pattern\"#"
    else
        echo "r\"$pattern\""
    fi
}

# Main generation function
generate() {
    cat <<EOF
// Code generated by generate.rs - DO NOT EDIT
// Source: patterns/*.yaml (hash: $patterns_hash)
// Generated: $timestamp

// Constants from patterns.yaml
EOF

    # Extract constants
    local long_threshold max_private_key_buffer
    long_threshold=$(yq '.constants.long_threshold' "$PATTERNS_DIR/patterns.yaml")
    max_private_key_buffer=$(yq '.constants.max_private_key_buffer' "$PATTERNS_DIR/patterns.yaml")

    echo "pub const LONG_THRESHOLD: usize = $long_threshold;"
    echo "pub const MAX_PRIVATE_KEY_BUFFER: usize = $max_private_key_buffer;"
    echo ""

    # Private key markers
    local pk_begin pk_end
    pk_begin=$(yq '.private_key.begin' "$PATTERNS_DIR/patterns.yaml")
    pk_end=$(yq '.private_key.end' "$PATTERNS_DIR/patterns.yaml")

    echo "// Private key markers (for streaming state machine)"
    echo "pub const PRIVATE_KEY_BEGIN: &str = $(rust_raw_string "$pk_begin");"
    echo "pub const PRIVATE_KEY_END: &str = $(rust_raw_string "$pk_end");"
    echo ""

    # Direct patterns (excluding multiline ones which need special handling)
    echo "/// Direct patterns: (regex, label)"
    echo "/// Match these patterns directly without context"
    echo "pub const PATTERNS: &[(&str, &str)] = &["

    # Use yq to iterate over patterns, filtering out multiline ones
    local pattern_count i pattern label
    pattern_count=$(yq '.patterns | map(select(.multiline != true)) | length' "$PATTERNS_DIR/patterns.yaml")
    for ((i=0; i<pattern_count; i++)); do
        pattern=$(yq -r ".patterns | map(select(.multiline != true)) | .[$i].pattern" "$PATTERNS_DIR/patterns.yaml")
        label=$(yq -r ".patterns | map(select(.multiline != true)) | .[$i].label" "$PATTERNS_DIR/patterns.yaml")
        echo "    ($(rust_raw_string "$pattern"), \"$label\"),"
    done

    echo "];"
    echo ""

    # Context patterns
    # Rust regex does NOT support lookbehind, so we use capture groups:
    # (prefix)(value) with the secret in group 2
    echo "/// Context patterns: (regex, label, capture_group)"
    echo "/// Rust regex lacks lookbehind - use capture groups instead"
    echo "/// The secret value is in the specified capture group"
    echo "pub const CONTEXT_PATTERNS: &[(&str, &str, usize)] = &["

    # Build context patterns with capture groups
    local context_count prefix value combined
    context_count=$(yq '.context_patterns | length' "$PATTERNS_DIR/patterns.yaml")
    for ((i=0; i<context_count; i++)); do
        prefix=$(yq -r ".context_patterns[$i].prefix" "$PATTERNS_DIR/patterns.yaml")
        value=$(yq -r ".context_patterns[$i].value" "$PATTERNS_DIR/patterns.yaml")
        label=$(yq -r ".context_patterns[$i].label" "$PATTERNS_DIR/patterns.yaml")
        combined="($prefix)($value)"
        echo "    ($(rust_raw_string "$combined"), \"$label\", 2),"
    done

    echo "];"
    echo ""

    # Special patterns as structs
    echo "/// Special pattern configuration"
    echo "#[derive(Debug, Clone)]"
    echo "pub struct SpecialPattern {"
    echo "    pub pattern: &'static str,"
    echo "    pub label: &'static str,"
    echo "    pub secret_group: usize,"
    echo "}"
    echo ""

    # Git credential pattern
    local git_pattern git_label git_group
    git_pattern=$(yq '.special_patterns.git_credential.pattern' "$PATTERNS_DIR/patterns.yaml")
    git_label=$(yq '.special_patterns.git_credential.label' "$PATTERNS_DIR/patterns.yaml")
    git_group=$(yq '.special_patterns.git_credential.secret_group' "$PATTERNS_DIR/patterns.yaml")

    echo "pub const GIT_CREDENTIAL_PATTERN: SpecialPattern = SpecialPattern {"
    echo "    pattern: $(rust_raw_string "$git_pattern"),"
    echo "    label: \"$git_label\","
    echo "    secret_group: $git_group,"
    echo "};"
    echo ""

    # Docker auth pattern
    local docker_pattern docker_label docker_group
    docker_pattern=$(yq '.special_patterns.docker_auth.pattern' "$PATTERNS_DIR/patterns.yaml")
    docker_label=$(yq '.special_patterns.docker_auth.label' "$PATTERNS_DIR/patterns.yaml")
    docker_group=$(yq '.special_patterns.docker_auth.secret_group' "$PATTERNS_DIR/patterns.yaml")

    echo "pub const DOCKER_AUTH_PATTERN: SpecialPattern = SpecialPattern {"
    echo "    pattern: $(rust_raw_string "$docker_pattern"),"
    echo "    label: \"$docker_label\","
    echo "    secret_group: $docker_group,"
    echo "};"
    echo ""

    # Environment variable explicit list
    echo "// Environment variable detection rules from env.yaml"
    echo ""
    echo "/// Explicit list of known secret variable names"
    echo "pub const EXPLICIT_ENV_VARS: &[&str] = &["

    local explicit_count var
    explicit_count=$(yq '.explicit | length' "$PATTERNS_DIR/env.yaml")
    for ((i=0; i<explicit_count; i++)); do
        var=$(yq -r ".explicit[$i]" "$PATTERNS_DIR/env.yaml")
        echo "    \"$var\","
    done

    echo "];"
    echo ""

    # Environment variable suffixes
    echo "/// Variable name suffixes that indicate secrets"
    echo "pub const ENV_SUFFIXES: &[&str] = &["

    local suffix_count suffix
    suffix_count=$(yq '.suffixes | length' "$PATTERNS_DIR/env.yaml")
    for ((i=0; i<suffix_count; i++)); do
        suffix=$(yq -r ".suffixes[$i]" "$PATTERNS_DIR/env.yaml")
        echo "    \"$suffix\","
    done

    echo "];"
    echo ""

    # Entropy configuration from entropy.yaml
    echo "// Entropy detection configuration from entropy.yaml"
    echo ""

    # Enabled by default
    local entropy_enabled
    entropy_enabled=$(yq '.enabled_by_default // false' "$PATTERNS_DIR/entropy.yaml")
    echo "pub const ENTROPY_ENABLED_DEFAULT: bool = $entropy_enabled;"
    echo ""

    # Thresholds
    local hex_threshold base64_threshold alphanumeric_threshold
    hex_threshold=$(yq '.thresholds.hex // 3.0' "$PATTERNS_DIR/entropy.yaml")
    base64_threshold=$(yq '.thresholds.base64 // 4.5' "$PATTERNS_DIR/entropy.yaml")
    alphanumeric_threshold=$(yq '.thresholds.alphanumeric // 4.5' "$PATTERNS_DIR/entropy.yaml")

    echo "/// Entropy thresholds by character set"
    echo "pub const ENTROPY_THRESHOLD_HEX: f64 = $hex_threshold;"
    echo "pub const ENTROPY_THRESHOLD_BASE64: f64 = $base64_threshold;"
    echo "pub const ENTROPY_THRESHOLD_ALPHANUMERIC: f64 = $alphanumeric_threshold;"
    echo ""

    # Token length constraints
    local min_length max_length
    min_length=$(yq '.token_length.min // 16' "$PATTERNS_DIR/entropy.yaml")
    max_length=$(yq '.token_length.max // 256' "$PATTERNS_DIR/entropy.yaml")

    echo "/// Token length constraints"
    echo "pub const ENTROPY_MIN_LENGTH: usize = $min_length;"
    echo "pub const ENTROPY_MAX_LENGTH: usize = $max_length;"
    echo ""

    # Exclusion pattern struct
    echo "/// Entropy exclusion pattern"
    echo "#[derive(Debug, Clone)]"
    echo "pub struct EntropyExclusion {"
    echo "    pub pattern: &'static str,"
    echo "    pub label: &'static str,"
    echo "    pub case_insensitive: bool,"
    echo "    pub context_keywords: Option<&'static [&'static str]>,"
    echo "}"
    echo ""

    # Exclusions array
    echo "/// Exclusion patterns for entropy detection"
    echo "pub const ENTROPY_EXCLUSIONS: &[EntropyExclusion] = &["

    local exclusion_count
    exclusion_count=$(yq '.exclusions | length' "$PATTERNS_DIR/entropy.yaml")
    for ((i=0; i<exclusion_count; i++)); do
        local excl_pattern excl_label case_insensitive context_kw_count
        excl_pattern=$(yq -r ".exclusions[$i].pattern" "$PATTERNS_DIR/entropy.yaml")
        excl_label=$(yq -r ".exclusions[$i].label" "$PATTERNS_DIR/entropy.yaml")
        case_insensitive=$(yq ".exclusions[$i].case_insensitive // false" "$PATTERNS_DIR/entropy.yaml")

        # Check for context keywords
        context_kw_count=$(yq ".exclusions[$i].context_keywords | length // 0" "$PATTERNS_DIR/entropy.yaml")

        echo "    EntropyExclusion {"
        echo "        pattern: $(rust_raw_string "$excl_pattern"),"
        echo "        label: \"$excl_label\","
        echo "        case_insensitive: $case_insensitive,"

        if [[ "$context_kw_count" -gt 0 ]]; then
            echo -n "        context_keywords: Some(&["
            for ((j=0; j<context_kw_count; j++)); do
                local kw
                kw=$(yq -r ".exclusions[$i].context_keywords[$j]" "$PATTERNS_DIR/entropy.yaml")
                [[ $j -gt 0 ]] && echo -n ", "
                echo -n "\"$kw\""
            done
            echo "]),"
        else
            echo "        context_keywords: None,"
        fi
        echo "    },"
    done

    echo "];"
    echo ""

    # Context keywords
    echo "/// Global context keywords for entropy detection"
    echo "pub const ENTROPY_CONTEXT_KEYWORDS: &[&str] = &["

    local ctx_kw_count
    ctx_kw_count=$(yq '.context_keywords | length' "$PATTERNS_DIR/entropy.yaml")
    for ((i=0; i<ctx_kw_count; i++)); do
        local kw
        kw=$(yq -r ".context_keywords[$i]" "$PATTERNS_DIR/entropy.yaml")
        echo "    \"$kw\","
    done

    echo "];"
}

# Generate output
generate > "$OUTPUT"

echo "Generated $OUTPUT (hash: $patterns_hash)"
