// Code generated by generate.go - DO NOT EDIT
// Generated: 2026-01-09T18:46:59Z
// Source: patterns/*.yaml (hash: cda5969325d4)
package main

import "regexp"

const LongThreshold = 50
const MaxPrivateKeyBuffer = 100

var (
	privateKeyBegin = regexp.MustCompile(`-----BEGIN [A-Z ]*PRIVATE KEY-----`)
	privateKeyEnd   = regexp.MustCompile(`-----END [A-Z ]*PRIVATE KEY-----`)
)

// Pattern holds a compiled regex and its label
type Pattern struct {
	Regex *regexp.Regexp
	Label string
}

// Direct patterns that can be matched without context
var patterns = []Pattern{
	{regexp.MustCompile(`ghp_[A-Za-z0-9]{36}`), "GITHUB_PAT"},
	{regexp.MustCompile(`gho_[A-Za-z0-9]{36}`), "GITHUB_OAUTH"},
	{regexp.MustCompile(`ghs_[A-Za-z0-9]{36}`), "GITHUB_SERVER"},
	{regexp.MustCompile(`ghr_[A-Za-z0-9]{36}`), "GITHUB_REFRESH"},
	{regexp.MustCompile(`github_pat_[A-Za-z0-9_]{22,}`), "GITHUB_PAT"},
	{regexp.MustCompile(`glpat-[A-Za-z0-9_-]{20,}`), "GITLAB_PAT"},
	{regexp.MustCompile(`xoxb-[0-9]+-[0-9A-Za-z-]+`), "SLACK_BOT"},
	{regexp.MustCompile(`xoxp-[0-9]+-[0-9A-Za-z-]+`), "SLACK_USER"},
	{regexp.MustCompile(`xoxa-[0-9]+-[0-9A-Za-z-]+`), "SLACK_APP"},
	{regexp.MustCompile(`xoxs-[0-9]+-[0-9A-Za-z-]+`), "SLACK_SESSION"},
	{regexp.MustCompile(`sk-[A-Za-z0-9]{48}`), "OPENAI_KEY"},
	{regexp.MustCompile(`sk-proj-[A-Za-z0-9_-]{20,}`), "OPENAI_PROJECT_KEY"},
	{regexp.MustCompile(`sk-ant-[A-Za-z0-9-]{90,}`), "ANTHROPIC_KEY"},
	{regexp.MustCompile(`AKIA[A-Z0-9]{16}`), "AWS_ACCESS_KEY"},
	{regexp.MustCompile(`AIza[A-Za-z0-9_-]{35}`), "GOOGLE_API_KEY"},
	{regexp.MustCompile(`AGE-SECRET-KEY-[A-Z0-9]{59}`), "AGE_SECRET_KEY"},
	{regexp.MustCompile(`sk_live_[A-Za-z0-9]{24,}`), "STRIPE_SECRET"},
	{regexp.MustCompile(`sk_test_[A-Za-z0-9]{24,}`), "STRIPE_TEST"},
	{regexp.MustCompile(`pk_live_[A-Za-z0-9]{24,}`), "STRIPE_PUBLISHABLE"},
	{regexp.MustCompile(`SK[a-f0-9]{32}`), "TWILIO_KEY"},
	{regexp.MustCompile(`SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+`), "SENDGRID_KEY"},
	{regexp.MustCompile(`npm_[A-Za-z0-9]{36}`), "NPM_TOKEN"},
	{regexp.MustCompile(`pypi-[A-Za-z0-9_-]{100,}`), "PYPI_TOKEN"},
	{regexp.MustCompile(`eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+`), "JWT_TOKEN"},
	{regexp.MustCompile(`dop_v1_[a-f0-9]{64}`), "DIGITALOCEAN_PAT"},
	{regexp.MustCompile(`doo_v1_[a-f0-9]{64}`), "DIGITALOCEAN_OAUTH"},
	{regexp.MustCompile(`dor_v1_[a-f0-9]{64}`), "DIGITALOCEAN_REFRESH"},
	{regexp.MustCompile(`HRKU-[A-Za-z0-9_]{60}`), "HEROKU_API_KEY"},
	{regexp.MustCompile(`GOCSPX-[A-Za-z0-9_-]{20,}`), "GCP_OAUTH_SECRET"},
	{regexp.MustCompile(`nfp_[A-Za-z0-9_-]{20,}`), "NETLIFY_PAT"},
	{regexp.MustCompile(`sb_publishable_[A-Za-z0-9_-]{20,}`), "SUPABASE_PUBLISHABLE"},
	{regexp.MustCompile(`sb_secret_[A-Za-z0-9_-]{20,}`), "SUPABASE_SECRET"},
	{regexp.MustCompile(`pscale_tkn_[A-Za-z0-9_-]{30,}`), "PLANETSCALE_TOKEN"},
	{regexp.MustCompile(`[A-Za-z0-9]{9}\.atlasv1\.[A-Za-z0-9]{40,}`), "TERRAFORM_CLOUD_TOKEN"},
	{regexp.MustCompile(`hvs\.[A-Za-z0-9]{24,}`), "VAULT_SERVICE_TOKEN"},
	{regexp.MustCompile(`hvb\.[A-Za-z0-9]{24,}`), "VAULT_BATCH_TOKEN"},
	{regexp.MustCompile(`hvr\.[A-Za-z0-9]{24,}`), "VAULT_RECOVERY_TOKEN"},
	{regexp.MustCompile(`rubygems_[a-f0-9]{56}`), "RUBYGEMS_API_KEY"},
	{regexp.MustCompile(`shpat_[A-Za-z0-9]{32,}`), "SHOPIFY_ADMIN_TOKEN"},
	{regexp.MustCompile(`NRAK-[A-Za-z0-9]{27,}`), "NEWRELIC_USER_KEY"},
	{regexp.MustCompile(`key-[A-Za-z0-9]{32,}`), "MAILGUN_API_KEY"},
	{regexp.MustCompile(`lin_api_[A-Za-z0-9]{40,}`), "LINEAR_API_KEY"},
	{regexp.MustCompile(`dp\.pt\.[A-Za-z0-9]{40,}`), "DOPPLER_TOKEN"},
	{regexp.MustCompile(`[0-9]{9,10}:[A-Za-z0-9_-]{35,}`), "TELEGRAM_BOT_TOKEN"},
	{regexp.MustCompile(`[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}`), "DISCORD_BOT_TOKEN"},
	{regexp.MustCompile(`https://discord\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+`), "DISCORD_WEBHOOK"},
	{regexp.MustCompile(`EAA[A-Za-z0-9]{50,}`), "FACEBOOK_ACCESS_TOKEN"},
}

// Context patterns require prefix context (use capture groups since Go RE2 has no lookbehind)
var contextPatterns = []struct {
	Regex *regexp.Regexp
	Label string
	Group int // which capture group contains the secret
}{
	{regexp.MustCompile(`(password )([^\s]+)`), "NETRC_PASSWORD", 2},
	{regexp.MustCompile(`(passwd )([^\s]+)`), "NETRC_PASSWORD", 2},
	{regexp.MustCompile(`(password=)([^\s,;"'\}\[\]]+)`), "PASSWORD_VALUE", 2},
	{regexp.MustCompile(`(password:)(\s*[^\s,;"'\}\[\]]+)`), "PASSWORD_VALUE", 2},
	{regexp.MustCompile(`(secret=)([^\s,;"'\}\[\]]+)`), "SECRET_VALUE", 2},
	{regexp.MustCompile(`(secret:)(\s*[^\s,;"'\}\[\]]+)`), "SECRET_VALUE", 2},
	{regexp.MustCompile(`(token=)([^\s,;"'\}\[\]]+)`), "TOKEN_VALUE", 2},
	{regexp.MustCompile(`(token:)(\s*[^\s,;"'\}\[\]]+)`), "TOKEN_VALUE", 2},
	{regexp.MustCompile(`(AccountKey=)([A-Za-z0-9+/]{88}==)`), "AZURE_STORAGE_KEY", 2},
	{regexp.MustCompile(`(Password=)([^\s,;"'\}\[\]]+)`), "PASSWORD_VALUE", 2},
	{regexp.MustCompile(`(Password:)(\s*[^\s,;"'\}\[\]]+)`), "PASSWORD_VALUE", 2},
	{regexp.MustCompile(`(Secret=)([^\s,;"'\}\[\]]+)`), "SECRET_VALUE", 2},
	{regexp.MustCompile(`(Secret:)(\s*[^\s,;"'\}\[\]]+)`), "SECRET_VALUE", 2},
	{regexp.MustCompile(`(Token=)([^\s,;"'\}\[\]]+)`), "TOKEN_VALUE", 2},
	{regexp.MustCompile(`(Token:)(\s*[^\s,;"'\}\[\]]+)`), "TOKEN_VALUE", 2},
}

// Special patterns with multiple capture groups
var (
	gitCredentialPattern = regexp.MustCompile(`(://[^:]+:)([^@]+)(@)`)
	dockerAuthPattern = regexp.MustCompile(`("auth":\s*")([A-Za-z0-9+/=]{20,})(")`)
)

// Explicit environment variable names known to contain secrets
var explicitEnvVars = map[string]bool{
	"GITHUB_TOKEN": true,
	"GH_TOKEN": true,
	"GITLAB_TOKEN": true,
	"GLAB_TOKEN": true,
	"BITBUCKET_TOKEN": true,
	"AWS_SECRET_ACCESS_KEY": true,
	"AWS_SESSION_TOKEN": true,
	"AZURE_CLIENT_SECRET": true,
	"OPENAI_API_KEY": true,
	"ANTHROPIC_API_KEY": true,
	"CLAUDE_API_KEY": true,
	"SLACK_TOKEN": true,
	"SLACK_BOT_TOKEN": true,
	"SLACK_WEBHOOK_URL": true,
	"NPM_TOKEN": true,
	"PYPI_TOKEN": true,
	"DOCKER_PASSWORD": true,
	"DATABASE_URL": true,
	"REDIS_URL": true,
	"MONGODB_URI": true,
	"JWT_SECRET": true,
	"SESSION_SECRET": true,
	"ENCRYPTION_KEY": true,
	"SENDGRID_API_KEY": true,
	"TWILIO_AUTH_TOKEN": true,
	"STRIPE_SECRET_KEY": true,
	"DIGITALOCEAN_TOKEN": true,
	"DIGITALOCEAN_ACCESS_TOKEN": true,
	"HEROKU_API_KEY": true,
	"HEROKU_AUTH_TOKEN": true,
	"NETLIFY_AUTH_TOKEN": true,
	"VERCEL_TOKEN": true,
	"CLOUDFLARE_API_TOKEN": true,
	"CLOUDFLARE_API_KEY": true,
	"SUPABASE_SERVICE_ROLE_KEY": true,
	"SUPABASE_ANON_KEY": true,
	"PLANETSCALE_SERVICE_TOKEN": true,
	"NEON_API_KEY": true,
	"VAULT_TOKEN": true,
	"TF_TOKEN": true,
	"TFC_TOKEN": true,
	"TERRAFORM_CLOUD_TOKEN": true,
	"CONSUL_HTTP_TOKEN": true,
	"DISCORD_TOKEN": true,
	"DISCORD_BOT_TOKEN": true,
	"TELEGRAM_BOT_TOKEN": true,
	"DATADOG_API_KEY": true,
	"DATADOG_APP_KEY": true,
	"NEW_RELIC_LICENSE_KEY": true,
	"NEWRELIC_API_KEY": true,
	"SENTRY_DSN": true,
	"SENTRY_AUTH_TOKEN": true,
	"GRAFANA_API_KEY": true,
	"LINEAR_API_KEY": true,
	"DOPPLER_TOKEN": true,
	"SHOPIFY_ACCESS_TOKEN": true,
	"SHOPIFY_API_KEY": true,
	"SHOPIFY_API_SECRET": true,
	"MAILGUN_API_KEY": true,
	"ALGOLIA_API_KEY": true,
	"ALGOLIA_ADMIN_KEY": true,
	"FACEBOOK_ACCESS_TOKEN": true,
}

// Suffixes that indicate secret environment variables
var envSuffixes = []string{
	"_SECRET",
	"_PASSWORD",
	"_TOKEN",
	"_API_KEY",
	"_PRIVATE_KEY",
	"_AUTH",
	"_CREDENTIAL",
}
