# Generated by generate.py - DO NOT EDIT
# Source hash: 24370795df96
# Generated: 2026-01-09T18:14:05Z
#
# This file is auto-generated from:
#   - patterns/patterns.yaml
#   - patterns/env.yaml
#
# To regenerate: python python/generate.py
"""Auto-generated pattern definitions for secrets-filter.

This module exports:
- PATTERNS: Direct regex patterns (regex_string, label)
- CONTEXT_PATTERNS: Patterns with lookbehind (regex_string, label)
- SPECIAL_PATTERNS: Complex patterns with capture groups
- PRIVATE_KEY_BEGIN, PRIVATE_KEY_END: Regex strings for state machine
- EXPLICIT_ENV_VARS: Set of known secret variable names
- ENV_SUFFIXES: Tuple of variable name suffixes indicating secrets
- LONG_THRESHOLD, MAX_PRIVATE_KEY_BUFFER: Integer constants
"""

# Constants
LONG_THRESHOLD = 50
MAX_PRIVATE_KEY_BUFFER = 100

# Direct patterns: (regex_string, label)
PATTERNS = [
    (r'ghp_[A-Za-z0-9]{36}', 'GITHUB_PAT'),
    (r'gho_[A-Za-z0-9]{36}', 'GITHUB_OAUTH'),
    (r'ghs_[A-Za-z0-9]{36}', 'GITHUB_SERVER'),
    (r'ghr_[A-Za-z0-9]{36}', 'GITHUB_REFRESH'),
    (r'github_pat_[A-Za-z0-9_]{22,}', 'GITHUB_PAT'),
    (r'glpat-[A-Za-z0-9_-]{20,}', 'GITLAB_PAT'),
    (r'xoxb-[0-9]+-[0-9A-Za-z-]+', 'SLACK_BOT'),
    (r'xoxp-[0-9]+-[0-9A-Za-z-]+', 'SLACK_USER'),
    (r'xoxa-[0-9]+-[0-9A-Za-z-]+', 'SLACK_APP'),
    (r'xoxs-[0-9]+-[0-9A-Za-z-]+', 'SLACK_SESSION'),
    (r'sk-[A-Za-z0-9]{48}', 'OPENAI_KEY'),
    (r'sk-proj-[A-Za-z0-9_-]{20,}', 'OPENAI_PROJECT_KEY'),
    (r'sk-ant-[A-Za-z0-9-]{90,}', 'ANTHROPIC_KEY'),
    (r'AKIA[A-Z0-9]{16}', 'AWS_ACCESS_KEY'),
    (r'AIza[A-Za-z0-9_-]{35}', 'GOOGLE_API_KEY'),
    (r'AGE-SECRET-KEY-[A-Z0-9]{59}', 'AGE_SECRET_KEY'),
    (r'sk_live_[A-Za-z0-9]{24,}', 'STRIPE_SECRET'),
    (r'sk_test_[A-Za-z0-9]{24,}', 'STRIPE_TEST'),
    (r'pk_live_[A-Za-z0-9]{24,}', 'STRIPE_PUBLISHABLE'),
    (r'SK[a-f0-9]{32}', 'TWILIO_KEY'),
    (r'SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', 'SENDGRID_KEY'),
    (r'npm_[A-Za-z0-9]{36}', 'NPM_TOKEN'),
    (r'pypi-[A-Za-z0-9_-]{100,}', 'PYPI_TOKEN'),
    (r'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', 'JWT_TOKEN'),
]

# Context patterns using lookbehind: (regex_string, label)
CONTEXT_PATTERNS = [
    (r'(?<=password )[^\s]+', 'NETRC_PASSWORD'),
    (r'(?<=passwd )[^\s]+', 'NETRC_PASSWORD'),
    ('(?<=password=)[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=password:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=secret=)[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=secret:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=token=)[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
    ('(?<=token:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
    ('(?<=Password=)[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=Password:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=Secret=)[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=Secret:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=Token=)[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
    ('(?<=Token:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
]

# Special patterns with capture groups
SPECIAL_PATTERNS = {
    'git_credential': {
        'pattern': r'(://[^:]+:)([^@]+)(@)',
        'label': 'GIT_CREDENTIAL',
        'secret_group': 2,
    },
    'docker_auth': {
        'pattern': r'("auth":\s*")([A-Za-z0-9+/=]{20,})(")',
        'label': 'DOCKER_AUTH',
        'secret_group': 2,
    },
}

# Private key markers for streaming state machine
PRIVATE_KEY_BEGIN = r'-----BEGIN [A-Z ]*PRIVATE KEY-----'
PRIVATE_KEY_END = r'-----END [A-Z ]*PRIVATE KEY-----'

# Environment variable detection
EXPLICIT_ENV_VARS = {
    'ANTHROPIC_API_KEY',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_SESSION_TOKEN',
    'AZURE_CLIENT_SECRET',
    'BITBUCKET_TOKEN',
    'CLAUDE_API_KEY',
    'DATABASE_URL',
    'DOCKER_PASSWORD',
    'ENCRYPTION_KEY',
    'GH_TOKEN',
    'GITHUB_TOKEN',
    'GITLAB_TOKEN',
    'GLAB_TOKEN',
    'JWT_SECRET',
    'MONGODB_URI',
    'NPM_TOKEN',
    'OPENAI_API_KEY',
    'PYPI_TOKEN',
    'REDIS_URL',
    'SENDGRID_API_KEY',
    'SESSION_SECRET',
    'SLACK_BOT_TOKEN',
    'SLACK_TOKEN',
    'SLACK_WEBHOOK_URL',
    'STRIPE_SECRET_KEY',
    'TWILIO_AUTH_TOKEN',
}

ENV_SUFFIXES = (
    '_SECRET',
    '_PASSWORD',
    '_TOKEN',
    '_API_KEY',
    '_PRIVATE_KEY',
    '_AUTH',
    '_CREDENTIAL',
)
