# Generated by generate.py - DO NOT EDIT
# Source hash: 97057734274b
# Generated: 2026-01-14T20:42:38Z
#
# This file is auto-generated from:
#   - patterns/patterns.yaml
#   - patterns/env.yaml
#   - patterns/entropy.yaml
#
# To regenerate: python python/generate.py
"""Auto-generated pattern definitions for kahl.

This module exports:
- PATTERNS: Direct regex patterns (regex_string, label)
- CONTEXT_PATTERNS: Patterns with lookbehind (regex_string, label)
- SPECIAL_PATTERNS: Complex patterns with capture groups
- PRIVATE_KEY_BEGIN, PRIVATE_KEY_END: Regex strings for state machine
- EXPLICIT_ENV_VARS: Set of known secret variable names
- ENV_SUFFIXES: Tuple of variable name suffixes indicating secrets
- LONG_THRESHOLD, MAX_PRIVATE_KEY_BUFFER: Integer constants
- ENTROPY_*: Entropy detection configuration
"""

# Constants
LONG_THRESHOLD = 50
MAX_PRIVATE_KEY_BUFFER = 100

# Direct patterns: (regex_string, label)
PATTERNS = [
    (r'ghp_[A-Za-z0-9]{36}', 'GITHUB_PAT'),
    (r'gho_[A-Za-z0-9]{36}', 'GITHUB_OAUTH'),
    (r'ghs_[A-Za-z0-9]{36}', 'GITHUB_SERVER'),
    (r'ghr_[A-Za-z0-9]{36}', 'GITHUB_REFRESH'),
    (r'github_pat_[A-Za-z0-9_]{22,}', 'GITHUB_PAT'),
    (r'glpat-[A-Za-z0-9_-]{20,}', 'GITLAB_PAT'),
    (r'xoxb-[0-9]+-[0-9A-Za-z-]+', 'SLACK_BOT'),
    (r'xoxp-[0-9]+-[0-9A-Za-z-]+', 'SLACK_USER'),
    (r'xoxa-[0-9]+-[0-9A-Za-z-]+', 'SLACK_APP'),
    (r'xoxs-[0-9]+-[0-9A-Za-z-]+', 'SLACK_SESSION'),
    (r'sk-[A-Za-z0-9]{48}', 'OPENAI_KEY'),
    (r'sk-proj-[A-Za-z0-9_-]{20,}', 'OPENAI_PROJECT_KEY'),
    (r'sk-ant-[A-Za-z0-9-]{90,}', 'ANTHROPIC_KEY'),
    (r'AKIA[A-Z0-9]{16}', 'AWS_ACCESS_KEY'),
    (r'AIza[A-Za-z0-9_-]{35}', 'GOOGLE_API_KEY'),
    (r'AGE-SECRET-KEY-[A-Z0-9]{59}', 'AGE_SECRET_KEY'),
    (r'sk_live_[A-Za-z0-9]{24,}', 'STRIPE_SECRET'),
    (r'sk_test_[A-Za-z0-9]{24,}', 'STRIPE_TEST'),
    (r'pk_live_[A-Za-z0-9]{24,}', 'STRIPE_PUBLISHABLE'),
    (r'SK[a-f0-9]{32}', 'TWILIO_KEY'),
    (r'SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', 'SENDGRID_KEY'),
    (r'npm_[A-Za-z0-9]{36}', 'NPM_TOKEN'),
    (r'pypi-[A-Za-z0-9_-]{100,}', 'PYPI_TOKEN'),
    (r'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', 'JWT_TOKEN'),
    (r'dop_v1_[a-f0-9]{64}', 'DIGITALOCEAN_PAT'),
    (r'doo_v1_[a-f0-9]{64}', 'DIGITALOCEAN_OAUTH'),
    (r'dor_v1_[a-f0-9]{64}', 'DIGITALOCEAN_REFRESH'),
    (r'HRKU-[A-Za-z0-9_]{60}', 'HEROKU_API_KEY'),
    (r'GOCSPX-[A-Za-z0-9_-]{20,}', 'GCP_OAUTH_SECRET'),
    (r'nfp_[A-Za-z0-9_-]{20,}', 'NETLIFY_PAT'),
    (r'sb_publishable_[A-Za-z0-9_-]{20,}', 'SUPABASE_PUBLISHABLE'),
    (r'sb_secret_[A-Za-z0-9_-]{20,}', 'SUPABASE_SECRET'),
    (r'pscale_tkn_[A-Za-z0-9_-]{30,}', 'PLANETSCALE_TOKEN'),
    (r'[A-Za-z0-9]{9}\.atlasv1\.[A-Za-z0-9]{40,}', 'TERRAFORM_CLOUD_TOKEN'),
    (r'hvs\.[A-Za-z0-9]{24,}', 'VAULT_SERVICE_TOKEN'),
    (r'hvb\.[A-Za-z0-9]{24,}', 'VAULT_BATCH_TOKEN'),
    (r'hvr\.[A-Za-z0-9]{24,}', 'VAULT_RECOVERY_TOKEN'),
    (r'rubygems_[a-f0-9]{56}', 'RUBYGEMS_API_KEY'),
    (r'shpat_[A-Za-z0-9]{32,}', 'SHOPIFY_ADMIN_TOKEN'),
    (r'NRAK-[A-Za-z0-9]{27,}', 'NEWRELIC_USER_KEY'),
    (r'key-[A-Za-z0-9]{32,}', 'MAILGUN_API_KEY'),
    (r'lin_api_[A-Za-z0-9]{40,}', 'LINEAR_API_KEY'),
    (r'dp\.pt\.[A-Za-z0-9]{40,}', 'DOPPLER_TOKEN'),
    (r'[0-9]{9,10}:[A-Za-z0-9_-]{35,}', 'TELEGRAM_BOT_TOKEN'),
    (r'[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}', 'DISCORD_BOT_TOKEN'),
    (r'https://discord\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+', 'DISCORD_WEBHOOK'),
    (r'EAA[A-Za-z0-9]{50,}', 'FACEBOOK_ACCESS_TOKEN'),
]

# Context patterns using lookbehind: (regex_string, label)
CONTEXT_PATTERNS = [
    (r'(?<=password )[^\s]+', 'NETRC_PASSWORD'),
    (r'(?<=passwd )[^\s]+', 'NETRC_PASSWORD'),
    ('(?<=password=)[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=password:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=secret=)[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=secret:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=token=)[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
    ('(?<=token:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
    (r'(?<=AccountKey=)[A-Za-z0-9+/]{88}==', 'AZURE_STORAGE_KEY'),
    ('(?<=Password=)[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=Password:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'PASSWORD_VALUE'),
    ('(?<=Secret=)[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=Secret:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'SECRET_VALUE'),
    ('(?<=Token=)[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
    ('(?<=Token:)\\s*[^\\s,;"\'\\}\\[\\]]+', 'TOKEN_VALUE'),
]

# Special patterns with capture groups
SPECIAL_PATTERNS = {
    'git_credential': {
        'pattern': r'(://[^:]+:)([^@]+)(@)',
        'label': 'GIT_CREDENTIAL',
        'secret_group': 2,
    },
    'docker_auth': {
        'pattern': r'("auth":\s*")([A-Za-z0-9+/=]{20,})(")',
        'label': 'DOCKER_AUTH',
        'secret_group': 2,
    },
}

# Private key markers for streaming state machine
PRIVATE_KEY_BEGIN = r'-----BEGIN [A-Z ]*PRIVATE KEY-----'
PRIVATE_KEY_END = r'-----END [A-Z ]*PRIVATE KEY-----'

# Environment variable detection
EXPLICIT_ENV_VARS = {
    'ALGOLIA_ADMIN_KEY',
    'ALGOLIA_API_KEY',
    'ANTHROPIC_API_KEY',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_SESSION_TOKEN',
    'AZURE_CLIENT_SECRET',
    'BITBUCKET_TOKEN',
    'CLAUDE_API_KEY',
    'CLOUDFLARE_API_KEY',
    'CLOUDFLARE_API_TOKEN',
    'CONSUL_HTTP_TOKEN',
    'DATABASE_URL',
    'DATADOG_API_KEY',
    'DATADOG_APP_KEY',
    'DIGITALOCEAN_ACCESS_TOKEN',
    'DIGITALOCEAN_TOKEN',
    'DISCORD_BOT_TOKEN',
    'DISCORD_TOKEN',
    'DOCKER_PASSWORD',
    'DOPPLER_TOKEN',
    'ENCRYPTION_KEY',
    'FACEBOOK_ACCESS_TOKEN',
    'GH_TOKEN',
    'GITHUB_TOKEN',
    'GITLAB_TOKEN',
    'GLAB_TOKEN',
    'GRAFANA_API_KEY',
    'HEROKU_API_KEY',
    'HEROKU_AUTH_TOKEN',
    'JWT_SECRET',
    'LINEAR_API_KEY',
    'MAILGUN_API_KEY',
    'MONGODB_URI',
    'NEON_API_KEY',
    'NETLIFY_AUTH_TOKEN',
    'NEWRELIC_API_KEY',
    'NEW_RELIC_LICENSE_KEY',
    'NPM_TOKEN',
    'OPENAI_API_KEY',
    'PLANETSCALE_SERVICE_TOKEN',
    'PYPI_TOKEN',
    'REDIS_URL',
    'SENDGRID_API_KEY',
    'SENTRY_AUTH_TOKEN',
    'SENTRY_DSN',
    'SESSION_SECRET',
    'SHOPIFY_ACCESS_TOKEN',
    'SHOPIFY_API_KEY',
    'SHOPIFY_API_SECRET',
    'SLACK_BOT_TOKEN',
    'SLACK_TOKEN',
    'SLACK_WEBHOOK_URL',
    'STRIPE_SECRET_KEY',
    'SUPABASE_ANON_KEY',
    'SUPABASE_SERVICE_ROLE_KEY',
    'TELEGRAM_BOT_TOKEN',
    'TERRAFORM_CLOUD_TOKEN',
    'TFC_TOKEN',
    'TF_TOKEN',
    'TWILIO_AUTH_TOKEN',
    'VAULT_TOKEN',
    'VERCEL_TOKEN',
}

ENV_SUFFIXES = (
    '_SECRET',
    '_PASSWORD',
    '_TOKEN',
    '_API_KEY',
    '_PRIVATE_KEY',
    '_AUTH',
    '_CREDENTIAL',
)

# Entropy detection configuration
ENTROPY_ENABLED_DEFAULT = False

ENTROPY_THRESHOLDS = {
    'hex': 3.0,
    'base64': 4.5,
    'alphanumeric': 4.5,
}

ENTROPY_MIN_LENGTH = 16
ENTROPY_MAX_LENGTH = 256

ENTROPY_EXCLUSIONS = [
    {
        'pattern': r'[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}',
        'label': 'UUID',
        'case_insensitive': True,
        'context_keywords': None,
    },
    {
        'pattern': r'[a-f0-9]{40}',
        'label': 'GIT_SHA',
        'case_insensitive': False,
        'context_keywords': ['commit', 'sha', 'hash', 'ref', 'oid', 'blob', 'tree', 'parent', 'HEAD', 'merge'],
    },
    {
        'pattern': r'[a-f0-9]{64}',
        'label': 'SHA256_HASH',
        'case_insensitive': False,
        'context_keywords': ['sha256', 'image', 'docker', 'digest', 'hash', 'checksum', 'layer'],
    },
    {
        'pattern': r'[a-f0-9]{32}',
        'label': 'MD5_HASH',
        'case_insensitive': False,
        'context_keywords': ['md5', 'hash', 'checksum', 'etag'],
    },
    {
        'pattern': r'sha256:[a-f0-9]{64}',
        'label': 'DOCKER_DIGEST',
        'case_insensitive': False,
        'context_keywords': None,
    },
    {
        'pattern': r'[0-9]+\.[0-9]+\.[0-9]+[a-f0-9]*',
        'label': 'VERSION_STRING',
        'case_insensitive': False,
        'context_keywords': None,
    },
]

ENTROPY_CONTEXT_KEYWORDS = {
    'blob',
    'build',
    'checksum',
    'commit',
    'digest',
    'docker',
    'etag',
    'guid',
    'hash',
    'id',
    'image',
    'layer',
    'oid',
    'ref',
    'revision',
    'sha',
    'tree',
    'uuid',
    'version',
}
