# Generated by generate.pl - DO NOT EDIT
# Source: patterns/*.yaml (hash: 07adc45cdd9f)
# Generated: 2026-01-09 18:14:06 UTC
package Patterns;

use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(
    @PATTERNS
    @CONTEXT_PATTERNS
    %SPECIAL_PATTERNS
    $PRIVATE_KEY_BEGIN
    $PRIVATE_KEY_END
    @EXPLICIT_ENV_VARS
    @ENV_SUFFIXES
    $LONG_THRESHOLD
    $MAX_PRIVATE_KEY_BUFFER
);

our %EXPORT_TAGS = (
    all => \@EXPORT_OK,
);

# Constants
our $LONG_THRESHOLD = 50;
our $MAX_PRIVATE_KEY_BUFFER = 100;

# Private key markers (for streaming state machine)
our $PRIVATE_KEY_BEGIN = qr/-----BEGIN [A-Z ]*PRIVATE KEY-----/;
our $PRIVATE_KEY_END = qr/-----END [A-Z ]*PRIVATE KEY-----/;

# Direct token patterns: [regex, label]
# Order: more specific patterns first
our @PATTERNS = (
    [qr/ghp_[A-Za-z0-9]{36}/, 'GITHUB_PAT'],
    [qr/gho_[A-Za-z0-9]{36}/, 'GITHUB_OAUTH'],
    [qr/ghs_[A-Za-z0-9]{36}/, 'GITHUB_SERVER'],
    [qr/ghr_[A-Za-z0-9]{36}/, 'GITHUB_REFRESH'],
    [qr/github_pat_[A-Za-z0-9_]{22,}/, 'GITHUB_PAT'],
    [qr/glpat-[A-Za-z0-9_-]{20,}/, 'GITLAB_PAT'],
    [qr/xoxb-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_BOT'],
    [qr/xoxp-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_USER'],
    [qr/xoxa-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_APP'],
    [qr/xoxs-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_SESSION'],
    [qr/sk-[A-Za-z0-9]{48}/, 'OPENAI_KEY'],
    [qr/sk-proj-[A-Za-z0-9_-]{20,}/, 'OPENAI_PROJECT_KEY'],
    [qr/sk-ant-[A-Za-z0-9-]{90,}/, 'ANTHROPIC_KEY'],
    [qr/AKIA[A-Z0-9]{16}/, 'AWS_ACCESS_KEY'],
    [qr/AIza[A-Za-z0-9_-]{35}/, 'GOOGLE_API_KEY'],
    [qr/AGE-SECRET-KEY-[A-Z0-9]{59}/, 'AGE_SECRET_KEY'],
    [qr/sk_live_[A-Za-z0-9]{24,}/, 'STRIPE_SECRET'],
    [qr/sk_test_[A-Za-z0-9]{24,}/, 'STRIPE_TEST'],
    [qr/pk_live_[A-Za-z0-9]{24,}/, 'STRIPE_PUBLISHABLE'],
    [qr/SK[a-f0-9]{32}/, 'TWILIO_KEY'],
    [qr/SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/, 'SENDGRID_KEY'],
    [qr/npm_[A-Za-z0-9]{36}/, 'NPM_TOKEN'],
    [qr/pypi-[A-Za-z0-9_-]{100,}/, 'PYPI_TOKEN'],
    [qr/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/, 'JWT_TOKEN'],
    [qr/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/, 'PRIVATE_KEY'],  # multiline
);

# Context patterns: [regex with lookbehind, label]
our @CONTEXT_PATTERNS = (
    [qr/(?<=password )[^\s]+/, 'NETRC_PASSWORD'],
    [qr/(?<=passwd )[^\s]+/, 'NETRC_PASSWORD'],
    [qr/(?<=password=)[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=password:)\s*[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=secret=)[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=secret:)\s*[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=token=)[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
    [qr/(?<=token:)\s*[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
    [qr/(?<=Password=)[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=Password:)\s*[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=Secret=)[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=Secret:)\s*[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=Token=)[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
    [qr/(?<=Token:)\s*[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
);

# Special patterns with capture groups
our %SPECIAL_PATTERNS = (
    docker_auth => {
        pattern => qr/("auth":\s*")([A-Za-z0-9+\/=]{20,})(")/,
        label => 'DOCKER_AUTH',
        secret_group => 2,
    },
    git_credential => {
        pattern => qr/(:\/\/[^:]+:)([^@]+)(@)/,
        label => 'GIT_CREDENTIAL',
        secret_group => 2,
    },
);

# Explicit environment variable names to check
our @EXPLICIT_ENV_VARS = qw(
    GITHUB_TOKEN
    GH_TOKEN
    GITLAB_TOKEN
    GLAB_TOKEN
    BITBUCKET_TOKEN
    AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN
    AZURE_CLIENT_SECRET
    OPENAI_API_KEY
    ANTHROPIC_API_KEY
    CLAUDE_API_KEY
    SLACK_TOKEN
    SLACK_BOT_TOKEN
    SLACK_WEBHOOK_URL
    NPM_TOKEN
    PYPI_TOKEN
    DOCKER_PASSWORD
    DATABASE_URL
    REDIS_URL
    MONGODB_URI
    JWT_SECRET
    SESSION_SECRET
    ENCRYPTION_KEY
    SENDGRID_API_KEY
    TWILIO_AUTH_TOKEN
    STRIPE_SECRET_KEY
);

# Environment variable name suffixes that indicate secrets
our @ENV_SUFFIXES = qw(
    _SECRET
    _PASSWORD
    _TOKEN
    _API_KEY
    _PRIVATE_KEY
    _AUTH
    _CREDENTIAL
);

1;
