# Generated by generate.pl - DO NOT EDIT
# Source: patterns/*.yaml (hash: edc6a8732bb5)
# Generated: 2026-01-15 08:40:25 UTC
package Patterns;

use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(
    @PATTERNS
    @CONTEXT_PATTERNS
    %SPECIAL_PATTERNS
    $PRIVATE_KEY_BEGIN
    $PRIVATE_KEY_END
    @EXPLICIT_ENV_VARS
    @ENV_SUFFIXES
    $LONG_THRESHOLD
    $MAX_PRIVATE_KEY_BUFFER
    $ENTROPY_ENABLED_DEFAULT
    %ENTROPY_THRESHOLDS
    $ENTROPY_MIN_LENGTH
    $ENTROPY_MAX_LENGTH
    @ENTROPY_EXCLUSIONS
    %ENTROPY_CONTEXT_KEYWORDS
);

our %EXPORT_TAGS = (
    all => \@EXPORT_OK,
);

# Constants
our $LONG_THRESHOLD = 50;
our $MAX_PRIVATE_KEY_BUFFER = 100;

# Private key markers (for streaming state machine)
our $PRIVATE_KEY_BEGIN = qr/-----BEGIN [A-Z ]*PRIVATE KEY-----/;
our $PRIVATE_KEY_END = qr/-----END [A-Z ]*PRIVATE KEY-----/;

# Direct token patterns: [regex, label]
# Order: more specific patterns first
our @PATTERNS = (
    [qr/ghp_[A-Za-z0-9]{36}/, 'GITHUB_PAT'],
    [qr/gho_[A-Za-z0-9]{36}/, 'GITHUB_OAUTH'],
    [qr/ghs_[A-Za-z0-9]{36}/, 'GITHUB_SERVER'],
    [qr/ghr_[A-Za-z0-9]{36}/, 'GITHUB_REFRESH'],
    [qr/github_pat_[A-Za-z0-9_]{22,}/, 'GITHUB_PAT'],
    [qr/glpat-[A-Za-z0-9_-]{20,}/, 'GITLAB_PAT'],
    [qr/xoxb-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_BOT'],
    [qr/xoxp-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_USER'],
    [qr/xoxa-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_APP'],
    [qr/xoxs-[0-9]+-[0-9A-Za-z-]+/, 'SLACK_SESSION'],
    [qr/sk-[A-Za-z0-9]{48}/, 'OPENAI_KEY'],
    [qr/sk-proj-[A-Za-z0-9_-]{20,}/, 'OPENAI_PROJECT_KEY'],
    [qr/sk-ant-[A-Za-z0-9-]{90,}/, 'ANTHROPIC_KEY'],
    [qr/AKIA[A-Z0-9]{16}/, 'AWS_ACCESS_KEY'],
    [qr/AIza[A-Za-z0-9_-]{35}/, 'GOOGLE_API_KEY'],
    [qr/AGE-SECRET-KEY-[A-Z0-9]{59}/, 'AGE_SECRET_KEY'],
    [qr/sk_live_[A-Za-z0-9]{24,}/, 'STRIPE_SECRET'],
    [qr/sk_test_[A-Za-z0-9]{24,}/, 'STRIPE_TEST'],
    [qr/pk_live_[A-Za-z0-9]{24,}/, 'STRIPE_PUBLISHABLE'],
    [qr/SK[a-f0-9]{32}/, 'TWILIO_KEY'],
    [qr/SG\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/, 'SENDGRID_KEY'],
    [qr/npm_[A-Za-z0-9]{36}/, 'NPM_TOKEN'],
    [qr/pypi-[A-Za-z0-9_-]{100,}/, 'PYPI_TOKEN'],
    [qr/eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/, 'JWT_TOKEN'],
    [qr/dop_v1_[a-f0-9]{64}/, 'DIGITALOCEAN_PAT'],
    [qr/doo_v1_[a-f0-9]{64}/, 'DIGITALOCEAN_OAUTH'],
    [qr/dor_v1_[a-f0-9]{64}/, 'DIGITALOCEAN_REFRESH'],
    [qr/HRKU-[A-Za-z0-9_]{60}/, 'HEROKU_API_KEY'],
    [qr/GOCSPX-[A-Za-z0-9_-]{20,}/, 'GCP_OAUTH_SECRET'],
    [qr/nfp_[A-Za-z0-9_-]{20,}/, 'NETLIFY_PAT'],
    [qr/sb_publishable_[A-Za-z0-9_-]{20,}/, 'SUPABASE_PUBLISHABLE'],
    [qr/sb_secret_[A-Za-z0-9_-]{20,}/, 'SUPABASE_SECRET'],
    [qr/pscale_tkn_[A-Za-z0-9_-]{30,}/, 'PLANETSCALE_TOKEN'],
    [qr/[A-Za-z0-9]{9}\.atlasv1\.[A-Za-z0-9]{40,}/, 'TERRAFORM_CLOUD_TOKEN'],
    [qr/hvs\.[A-Za-z0-9]{24,}/, 'VAULT_SERVICE_TOKEN'],
    [qr/hvb\.[A-Za-z0-9]{24,}/, 'VAULT_BATCH_TOKEN'],
    [qr/hvr\.[A-Za-z0-9]{24,}/, 'VAULT_RECOVERY_TOKEN'],
    [qr/rubygems_[a-f0-9]{56}/, 'RUBYGEMS_API_KEY'],
    [qr/shpat_[A-Za-z0-9]{32,}/, 'SHOPIFY_ADMIN_TOKEN'],
    [qr/NRAK-[A-Za-z0-9]{27,}/, 'NEWRELIC_USER_KEY'],
    [qr/key-[A-Za-z0-9]{32,}/, 'MAILGUN_API_KEY'],
    [qr/lin_api_[A-Za-z0-9]{40,}/, 'LINEAR_API_KEY'],
    [qr/dp\.pt\.[A-Za-z0-9]{40,}/, 'DOPPLER_TOKEN'],
    [qr/[0-9]{9,10}:[A-Za-z0-9_-]{35,}/, 'TELEGRAM_BOT_TOKEN'],
    [qr/[MN][A-Za-z0-9]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}/, 'DISCORD_BOT_TOKEN'],
    [qr/https:\/\/discord\.com\/api\/webhooks\/[0-9]+\/[A-Za-z0-9_-]+/, 'DISCORD_WEBHOOK'],
    [qr/EAA[A-Za-z0-9]{50,}/, 'FACEBOOK_ACCESS_TOKEN'],
    [qr/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/, 'PRIVATE_KEY'],  # multiline
);

# Context patterns: [regex with lookbehind, label]
our @CONTEXT_PATTERNS = (
    [qr/(?<=password )[^\s]+/, 'NETRC_PASSWORD'],
    [qr/(?<=passwd )[^\s]+/, 'NETRC_PASSWORD'],
    [qr/(?<=password=)[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=password:)\s*[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=secret=)[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=secret:)\s*[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=token=)[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
    [qr/(?<=token:)\s*[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
    [qr/(?<=AccountKey=)[A-Za-z0-9+\/]{88}==/, 'AZURE_STORAGE_KEY'],
    [qr/(?<=Password=)[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=Password:)\s*[^\s,;"'\}\[\]]+/, 'PASSWORD_VALUE'],
    [qr/(?<=Secret=)[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=Secret:)\s*[^\s,;"'\}\[\]]+/, 'SECRET_VALUE'],
    [qr/(?<=Token=)[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
    [qr/(?<=Token:)\s*[^\s,;"'\}\[\]]+/, 'TOKEN_VALUE'],
);

# Special patterns with capture groups
our %SPECIAL_PATTERNS = (
    docker_auth => {
        pattern => qr/("auth":\s*")([A-Za-z0-9+\/=]{20,})(")/,
        label => 'DOCKER_AUTH',
        secret_group => 2,
    },
    git_credential => {
        pattern => qr/(:\/\/[^:]+:)([^@]+)(@)/,
        label => 'GIT_CREDENTIAL',
        secret_group => 2,
    },
);

# Explicit environment variable names to check
our @EXPLICIT_ENV_VARS = qw(
    GITHUB_TOKEN
    GH_TOKEN
    GITLAB_TOKEN
    GLAB_TOKEN
    BITBUCKET_TOKEN
    AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN
    AZURE_CLIENT_SECRET
    OPENAI_API_KEY
    ANTHROPIC_API_KEY
    CLAUDE_API_KEY
    SLACK_TOKEN
    SLACK_BOT_TOKEN
    SLACK_WEBHOOK_URL
    NPM_TOKEN
    PYPI_TOKEN
    DOCKER_PASSWORD
    DATABASE_URL
    REDIS_URL
    MONGODB_URI
    JWT_SECRET
    SESSION_SECRET
    ENCRYPTION_KEY
    SENDGRID_API_KEY
    TWILIO_AUTH_TOKEN
    STRIPE_SECRET_KEY
    DIGITALOCEAN_TOKEN
    DIGITALOCEAN_ACCESS_TOKEN
    HEROKU_API_KEY
    HEROKU_AUTH_TOKEN
    NETLIFY_AUTH_TOKEN
    VERCEL_TOKEN
    CLOUDFLARE_API_TOKEN
    CLOUDFLARE_API_KEY
    SUPABASE_SERVICE_ROLE_KEY
    SUPABASE_ANON_KEY
    PLANETSCALE_SERVICE_TOKEN
    NEON_API_KEY
    VAULT_TOKEN
    TF_TOKEN
    TFC_TOKEN
    TERRAFORM_CLOUD_TOKEN
    CONSUL_HTTP_TOKEN
    DISCORD_TOKEN
    DISCORD_BOT_TOKEN
    TELEGRAM_BOT_TOKEN
    DATADOG_API_KEY
    DATADOG_APP_KEY
    NEW_RELIC_LICENSE_KEY
    NEWRELIC_API_KEY
    SENTRY_DSN
    SENTRY_AUTH_TOKEN
    GRAFANA_API_KEY
    LINEAR_API_KEY
    DOPPLER_TOKEN
    SHOPIFY_ACCESS_TOKEN
    SHOPIFY_API_KEY
    SHOPIFY_API_SECRET
    MAILGUN_API_KEY
    ALGOLIA_API_KEY
    ALGOLIA_ADMIN_KEY
    FACEBOOK_ACCESS_TOKEN
);

# Environment variable name suffixes that indicate secrets
our @ENV_SUFFIXES = qw(
    _SECRET
    _PASSWORD
    _TOKEN
    _API_KEY
    _PRIVATE_KEY
    _AUTH
    _CREDENTIAL
);

# Entropy detection configuration
our $ENTROPY_ENABLED_DEFAULT = 0;

our %ENTROPY_THRESHOLDS = (
    hex => 3.0,
    base64 => 4.5,
    alphanumeric => 4.5,
);

our $ENTROPY_MIN_LENGTH = 16;
our $ENTROPY_MAX_LENGTH = 256;

our @ENTROPY_EXCLUSIONS = (
    {
        pattern => qr/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/i,
        label => 'UUID',
        case_insensitive => 1,
        context_keywords => undef,
    },
    {
        pattern => qr/[a-f0-9]{40}/,
        label => 'GIT_SHA',
        case_insensitive => 0,
        context_keywords => [qw(commit sha hash ref oid blob tree parent HEAD merge)],
    },
    {
        pattern => qr/[a-f0-9]{64}/,
        label => 'SHA256_HASH',
        case_insensitive => 0,
        context_keywords => [qw(sha256 image docker digest hash checksum layer)],
    },
    {
        pattern => qr/[a-f0-9]{32}/,
        label => 'MD5_HASH',
        case_insensitive => 0,
        context_keywords => [qw(md5 hash checksum etag)],
    },
    {
        pattern => qr/sha256:[a-f0-9]{64}/,
        label => 'DOCKER_DIGEST',
        case_insensitive => 0,
        context_keywords => undef,
    },
    {
        pattern => qr/[0-9]+\.[0-9]+\.[0-9]+[a-f0-9]*/,
        label => 'VERSION_STRING',
        case_insensitive => 0,
        context_keywords => undef,
    },
);

our %ENTROPY_CONTEXT_KEYWORDS = map { $_ => 1 } qw(
    blob
    build
    checksum
    commit
    digest
    docker
    etag
    guid
    hash
    id
    image
    layer
    oid
    ref
    revision
    sha
    tree
    uuid
    version
);

1;
